name: WorldEditGlobalizer Build

on:
  push:
    branches: [ dev-3.1.0-beta ]
  pull_request:
    branches: [ dev-3.1.0-beta ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: |
            build/libs
